# .github/workflows/commit-analytics.yml
name: Commit Analytics Data

on:
  schedule:
    # Run every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  commit-analytics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check for analytics file
        id: check-file
        run: |
          if [[ -f "data/analytics.json" ]]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit analytics data
        if: steps.check-file.outputs.file_exists == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/analytics.json
          git diff --staged --quiet || git commit -m "Update analytics data [skip ci]"
          git push
